<?php
include_once 'casconnect.php';
include_once 'dbconnect.php';


/**************************************
htmlallentities($str)


***************************************/
function htmlallentities($str){
  $res = '';
  $strlen = strlen($str);
  for($i=0; $i<$strlen; $i++){
    $byte = ord($str[$i]);
    if($byte < 128) // 1-byte char
      $res .= $str[$i];
    elseif($byte < 192); // invalid utf8
    elseif($byte < 224) // 2-byte char
      $res .= '&#'.((63&$byte)*64 + (63&ord($str[++$i]))).';';
    elseif($byte < 240) // 3-byte char
      $res .= '&#'.((15&$byte)*4096 + (63&ord($str[++$i]))*64 + (63&ord($str[++$i]))).';';
    elseif($byte < 248) // 4-byte char
      $res .= '&#'.((15&$byte)*262144 + (63&ord($str[++$i]))*4096 + (63&ord($str[++$i]))*64 + (63&ord($str[++$i]))).';';
  }
  return $res;
}

/**************************************
create_message($filename, $data)

This function will parse through a file '$filename' and replace all template variables with values found in $data.
EG. {{myvalue}} will be replaced by the value of an array element ['myvalue'] found in data. 
If ['myvalue'] is not found for any location requested, it will remain. The user is responsible for verifying complete replacement if desired.

***************************************/
function create_message($filename, $data){
	$sample = file_get_contents($filename);
	if ($sample === FALSE){
		return 'File not found!<BR>';
	} else {
		foreach ($data as $k => $v) {	
		$sample =  str_replace('{{' . $k . '}}', $v , $sample);
		}
		return htmlallentities($sample);
	}
}

/**************************************
email_message($subject, $email, $body)

This function uses the standard php mail() function to send and email. It returns a 0 on success and a 1 on failure.
This function has hard coded header information for this specific webpage.

***************************************/
function email_message($subject, $email, $body){
	//set the from line to know this was autogenerated
	$headers = "From: Achievements Admin <achievements@engr.oregonstate.edu>\r\n";
	$headers .= "BCC: heer@eecs.oregonstate.edu\r\n";
	$headers .= "Content-Type: text/html;charset=iso-8859-1\r\n";
	if(mail($email, $subject, wordwrap($body), $headers) ){
		echo "<p>Email Sent</p>";
		return 0;
	} else {
		echo "<p><B>Email not Sent</b></p>";
		return 1;
	}	
}

/**************************************
achievementlist($mysqli, $onid)

Returns an Array() of all achievements for $onid name given. 
Must be passed a valid mysqli object for database access
Returns null if onid id not found. 
Returns an empty Array if onid found but has not achievements.

***************************************/
function achievementlist($mysqli, $onid){
	$query = "SELECT * FROM users WHERE onid = '$onid'";
	$result = $mysqli->query($query);
	if ($result == NULL)
		return NULL;
	$row = $result->fetch_array();
	$achievements = unserialize($row['achievements']);
	if (empty($achievements))
		return $achievements;
	$returnvalue = Array();
	foreach ($achievements AS $id){
		$query = "SELECT levels.id, levels.level, levels.image, achievementList.name FROM levels INNER JOIN achievementList ON levels.achievementid = achievementList.id WHERE levels.id = $id ORDER BY achievementList.name ASC";
		//echo $query . '<BR>';
		$result = $mysqli->query($query);
		$row = $result->fetch_assoc();
		$returnvalue[$id] = $row; 
	}
	return $returnvalue;
}



$onid = phpCAS::getUser();
$res = $mysqli->query("SELECT * FROM users WHERE onid='$onid'");
$userrow = $res->fetch_array(MYSQLI_ASSOC);		//keep an array of elements in the user's table for easy access

if (isset($_REQUEST['logout'])) {
	phpCAS::logoutWithRedirectService('http://eecs.oregonstate.edu/education/achievements2');
}

echo '<!DOCTYPE html>
	<html>
	<center>
	<head>
	<title>Collaboratory Achievement Management</title>
	<LINK REL=StyleSheet HREF="style.css" TYPE="text/css">
	<script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>';
echo '<h1>Collaboratory Achievement Management</h1>
	<h2>Logged in as ', $userrow['username'], '</h2>';
echo '<header>
	<div class="nav">
	<nav>
	<ul>
	<li><a href="home.php">Home</a></li>
	<li><a href="approvals.php">Approvals</a></li>
	<li><a href="browse.php">Browse</a></li>
	<li><a href="achievements.php">Achievements</a></li>
	<li><a href="', $_SERVER['PHP_SELF'], '?logout">Logout</a></li>
	</ul></nav></div></header>';
?>
