<?php
/**************************************
htmlallentities($str)


***************************************/
function htmlallentities($str){
  $res = '';
  $strlen = strlen($str);
  for($i=0; $i<$strlen; $i++){
    $byte = ord($str[$i]);
    if($byte < 128) // 1-byte char
      $res .= $str[$i];
    elseif($byte < 192); // invalid utf8
    elseif($byte < 224) // 2-byte char
      $res .= '&#'.((63&$byte)*64 + (63&ord($str[++$i]))).';';
    elseif($byte < 240) // 3-byte char
      $res .= '&#'.((15&$byte)*4096 + (63&ord($str[++$i]))*64 + (63&ord($str[++$i]))).';';
    elseif($byte < 248) // 4-byte char
      $res .= '&#'.((15&$byte)*262144 + (63&ord($str[++$i]))*4096 + (63&ord($str[++$i]))*64 + (63&ord($str[++$i]))).';';
  }
  return $res;
}

/**************************************
create_message($filename, $data)

This function will parse through a file '$filename' and replace all template variables with values found in $data.
EG. {{myvalue}} will be replaced by the value of an array element ['myvalue'] found in data. 
If ['myvalue'] is not found for any location requested, it will remain. The user is responsible for verifying complete replacement if desired.

***************************************/
function create_message($filename, $data){
	$sample = file_get_contents($filename);
	if ($sample === FALSE){
		return 'File not found!<BR>';
	} else {
		foreach ($data as $k => $v) {	
		$sample =  str_replace('{{' . $k . '}}', $v , $sample);
		}
		return htmlallentities($sample);
	}
}

/**************************************
email_message($subject, $email, $body)

This function uses the standard php mail() function to send and email. It returns a 0 on success and a 1 on failure.
This function has hard coded header information for this specific webpage.

***************************************/
function email_message($subject, $email, $body){
	//set the from line to know this was autogenerated
	$headers = "From: Achievements Admin <achievements@engr.oregonstate.edu>\r\n";
	$headers .= "BCC: heer@eecs.oregonstate.edu\r\n";
	$headers .= "Content-Type: text/html;charset=iso-8859-1\r\n";
	if(mail($email, $subject, wordwrap($body), $headers) ){
		echo "<p>Email Sent</p>";
		return 0;
	} else {
		echo "<p><B>Email not Sent</b></p>";
		return 1;
	}	
}

/**************************************
achievementlist($mysqli, $onid)

Returns an Array() of all achievements for $onid name given. 
Must be passed a valid mysqli object for database access
Returns null if onid id not found. 
Returns an empty Array if onid found but has not achievements.

***************************************/
function achievementlist($mysqli, $onid){
	$query = "SELECT * FROM users WHERE onid = '$onid'";
	$result = $mysqli->query($query);
	if ($result == NULL)
		return NULL;
	$row = $result->fetch_array();
	$achievements = unserialize($row['achievements']);
	if (empty($achievements))
		return $achievements;
	$returnvalue = Array();
	foreach ($achievements AS $id){
		$query = "SELECT levels.id, levels.level, levels.image, achievementList.name FROM levels INNER JOIN achievementList ON levels.achievementid = achievementList.id WHERE levels.id = $id ORDER BY achievementList.name ASC";
		//echo $query . '<BR>';
		$result = $mysqli->query($query);
		$row = $result->fetch_assoc();
		$returnvalue[] = $row; 
	}
	return $returnvalue;
}

/**************************************
requestslist($mysqli, $onid)

Returns an Array() of all active reviews for $onid name given. 
Must be passed a valid mysqli object for database access
Returns null if onid id not found. 
Returns an empty Array if onid found but has no open reviews.

***************************************/
function requestslist($mysqli, $onid){
	$query = "SELECT * FROM users WHERE onid = '$onid'";
	$result = $mysqli->query($query);
	if ($result == NULL)
		return NULL;
	$row = $result->fetch_array();
	$myid = $row['id'];
	$query = "SELECT reviews.*, users.username, requests.evidence, requests.achievementid FROM reviews 
	INNER JOIN requests ON requests.id = reviews.requestid 
	INNER JOIN users ON users.id = requests.requesterid 
	WHERE reviews.reviewer = $myid AND reviews.completeddate IS NULL";
	//echo $query . '<BR>';
	$result = $mysqli->query($query);
	if ($result == NULL)
		return NULL;
	if ($result->num_rows == 0)
		return Array();
	
	$returnvalue = Array();
	while($row = $result->fetch_array()){
		$returnvalue[] = $row; 
	}
	return $returnvalue;
}


function randomhash() {
    $alphabet = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890';
    $pass = array(); //remember to declare $pass as an array
    $alphaLength = strlen($alphabet) - 1; //put the length -1 in cache
    for ($i = 0; $i < 16; $i++) {
        $n = rand(0, $alphaLength);
        $pass[] = $alphabet[$n];
    }
    return implode($pass); //turn the array into a string
}

?>
